services:
  tekkom-bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app

  tekkom-bot-api:
    container_name: tekkom-bot-api 
    image: tekkom-bot-api
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      DB: ${DB}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      AUTHENTIK_API_URL: ${AUTHENTIK_API_URL}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      QUEENBEE_URL: ${QUEENBEE_URL}
      REDIRECT_URI: ${REDIRECT_URI}

  postgres:
    image: postgres:15
    container_name: tekkom-bot_database
    restart: always
    environment:
      POSTGRES_USER: tekkom
      POSTGRES_PASSWORD: tekkom
      POSTGRES_DB: tekkom
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tekkom -d tekkom"]
      interval: 5s
      retries: 5

volumes:
  postgres_data:
